static OneParam defaultParams[] =
{
  {"A_1",              "lf", "0.01",       offsetof(Params, A_1)},
  {"fA",               "lf", "0.1",         offsetof(Params, fA)},
  {"B_1",              "lf", "0.015",       offsetof(Params, B_1)},
  {"Dc_1",             "lf", "1.0e-5",      offsetof(Params, Dc_1)},
  {"mu0_1",            "lf", "0.6",         offsetof(Params, mu0_1)},
  {"ddotStar_1",       "lf", "1.0e-6",      offsetof(Params, ddotStar_1)},
  {"ddotAB_1",         "lf", "1.0e-6",      offsetof(Params, ddotAB_1)},
  {"alpha_1",          "lf", "0.25",         offsetof(Params, alpha_1)},
  {"theta0_1",         "lf", "2.0e8",       offsetof(Params, theta0_1)},
  {"tau0_1",           "lf", "60.0",         offsetof(Params, tau0_1)},
  {"sigma0_1",         "lf", "100.0",       offsetof(Params, sigma0_1)},
  {"sigmaFracPin",     "lf", "0.1",         offsetof(Params, sigmaFracPin)},
  {"muPin",            "lf", "0.0",         offsetof(Params, muPin)},
  {"maxThetaPin",      "lf", "1e10",         offsetof(Params, maxThetaPin)},
  {"ddotEQ_1",          "lf", "1.0",         offsetof(Params, ddotEQ_1)},
  {"ddotEQFname",       "s",  "",           offsetof(Params, ddotEQFname)},
  {"stressOvershootFactor", "lf", "0.10",   offsetof(Params, stressOvershootFactor)},
  {"lameLambda",       "lf", "1.0e4",       offsetof(Params, lameLambda)},
  {"lameMu",           "lf", "1.0e4",       offsetof(Params, lameMu)},
  {"slowSlip_1",         "d",  "0",           offsetof(Params, slowSlip_1)},
  {"nEq",               "lf", "100000",      offsetof(Params, nEq)},
  {"tStart",           "lf", "0.0",         offsetof(Params, tStart)},
  {"maxT",             "lf", "1e100",        offsetof(Params, maxT)},
  {"maxTrans",         "lf", "1e10",        offsetof(Params, maxTrans)},
  {"faultFname",        "s", "faults.in",   offsetof(Params, faultFname)},
  {"outFnameInfix",     "s", "",            offsetof(Params, outFnameInfix)},
  {"writeTau",          "d", "0",           offsetof(Params, writeTau)},
  {"writeSigma",        "d", "0",           offsetof(Params, writeSigma)},
  {"writeSlip",         "d", "0",           offsetof(Params, writeSlip)},
  {"writeSlipSpeed",    "d", "0",           offsetof(Params, writeSlipSpeed)},
  {"writeState",        "d", "0",           offsetof(Params, writeState)},
  {"writeTheta",        "d", "0",           offsetof(Params, writeTheta)},
  {"writePED",          "d", "1",           offsetof(Params, writePED)},
  {"writeTransitions",  "d", "1",           offsetof(Params, writeTransitions)},
  {"minDtWrite",        "lf","0.0",         offsetof(Params, minDtWrite)},
  {"minDtWriteCoseismic", "lf","0.0",       offsetof(Params, minDtWriteCoseismic)},
  {"minDtWriteInterseismic", "lf","0.0",    offsetof(Params, minDtWriteInterseismic)},
  {"minMagWrite",       "lf","0.0",         offsetof(Params, minMagWrite)},
  {"writeStiffness",    "d", "0",           offsetof(Params, writeStiffness)},
  {"stressRateSpecification", "d", "1",     offsetof(Params, stressRateSpecification)},
  {"dMu3",              "lf","0.001",       offsetof(Params, dMu3)},
  {"initTauFname",      "s", "",            offsetof(Params, initTauFname)},
  {"initSigmaFname",    "s", "",            offsetof(Params, initSigmaFname)},
  {"initThetaFname",    "s", "",            offsetof(Params, initThetaFname)},
  {"initSlipSpeedFname","s", "",            offsetof(Params, initSlipSpeedFname)},
  {"AFname",            "s", "",            offsetof(Params, AFname)},
  {"BFname",            "s", "",            offsetof(Params, BFname)},
  {"DcFname",           "s", "",            offsetof(Params, DcFname)},
  {"mu0Fname",          "s", "",            offsetof(Params, mu0Fname)},
  {"ddotStarFname",     "s", "",            offsetof(Params, ddotStarFname)},
  {"ddotABFname",       "s", "",            offsetof(Params, ddotABFname)},
  {"alphaFname",        "s", "",            offsetof(Params, alphaFname)},
  {"KTauFname",         "s", "",            offsetof(Params, KTauFname)},
  {"KSigmaFname",       "s", "",            offsetof(Params, KSigmaFname)},
  {"tFailFname",        "s", "",            offsetof(Params, tFailFname)},
  {"tauFailFname",      "s", "",            offsetof(Params, tauFailFname)},
  {"tauDotFname",       "s", "",            offsetof(Params, tauDotFname)},
  {"sigmaDotFname",     "s", "",            offsetof(Params, sigmaDotFname)},
  {"pinnedFname",       "s", "",            offsetof(Params, pinnedFname)},
  {"neighborFname",     "s", "",            offsetof(Params, neighborFname)},
  {"stressRateFname",   "s", "",            offsetof(Params, stressRateFname)},
  {"slowSlipFname",     "s", "",            offsetof(Params, slowSlipFname)},
  {"writePatchFname",   "s", "",            offsetof(Params, writePatchFname)},
  {"DEBUG",             "d", "0",           offsetof(Params, DEBUG)},
  {"ZBrentUpperBracket","lf","0.0",         offsetof(Params, ZBrentUpperBracket)},
  {"ZBrentTol",         "lf","1.0e-6",      offsetof(Params, ZBrentTol)},
  {"lowSigmaAction",    "d", "0",           offsetof(Params, lowSigmaAction)},
  {"KZeroFrac",         "lf","0.0",         offsetof(Params, KZeroFrac)},
  {"KZeroFname",        "s","",             offsetof(Params, KZeroFname)},
  {"slipInState1",      "d", "1",           offsetof(Params, slipInState1)},
  {"resetStressingRates","d", "1",          offsetof(Params, resetStressingRates)},
  {"pointSource",        "d", "0",          offsetof(Params, pointSource)},
  {"tgfDist1",          "lf","20.0",        offsetof(Params, tgfDist1)},
  {"tgfDist2",          "lf","100.0",       offsetof(Params, tgfDist2)},
  {"nbuffEQS",           "d", "500",        offsetof(Params, nbuffEQS)},
  {"nbuffPED",           "d", "500",        offsetof(Params, nbuffPED)},
  {"nbuffTRANS",         "d", "500",        offsetof(Params, nbuffTRANS)},
  {"nbuffSnap",          "d", "500",        offsetof(Params, nbuffSnap)},
  {"maxTimeStep",        "lf","0.0",        offsetof(Params, maxTimeStep)},
  {"extStressRateFname", "s", "",           offsetof(Params, extStressRateFname)},
  {"unreduceAFix",       "d", "1",          offsetof(Params, unreduceAFix)},
  {"aReduceNmax",        "lf", "0",         offsetof(Params, aReduceNmax)},  
  {"aReduceN1",          "lf", "0",         offsetof(Params, aReduceN1)}, 
  {"aReduceN2",          "lf", "0",         offsetof(Params, aReduceN2)}, 
  {"fAmin",              "lf", "0.01",      offsetof(Params, fAmin)},
  {"maxDt1Zero",         "d", "1000000",    offsetof(Params, maxDt1Zero)}
 
};
